version: "3"

services:
  app:
    container_name: "202210_nextjs"
    build:
      context: ./app
    volumes:
      - ./app:/app/
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 3m
